### ISSUE TITLE
Can't build the plugin

### ISSUE THREAD

**Issue by dppeykov** [mattiarossi/packer-builder-oracle-ocisurrogate#1]
Hello,

I've been trying to build the plugin, but it is giving me the following errors:

_# github.com/mattiarossi/packer-builder-oracle-ocisurrogate/pkg/ocisurrogate
../../go/pkg/mod/github.com/mattiarossi/packer-builder-oracle-ocisurrogate@v0.0.0-20200322093732-3348fc83dd2a/pkg/ocisurrogate/driver_oci.go:74:6: cannot use &d.cfg.BootVolumeSizeInGBs (type *int64) as type *int in field value
../../go/pkg/mod/github.com/mattiarossi/packer-builder-oracle-ocisurrogate@v0.0.0-20200322093732-3348fc83dd2a/pkg/ocisurrogate/driver_oci.go:130:5: cannot use &d.cfg.BootVolumeSizeInGBs (type *int64) as type *int in field value_

I'm using OEL 7 (CentOS 7) - go version go1.14.1 linux/amd64.

Unfortunately, I'm not very familiar with Go, so can you have a look on the issue?

**Comment by mattiarossi** [comment]
Hi,
just noticed that Packer v1.5 has introduced breaking changes on the plugin side, for now, I have committed a change that forces building using packer v1.4
Could you pull the new version and give it a try?

**Comment by dppeykov** [comment]
It is fine with 1.4. 
Thanks!
