### ISSUE TITLE
Update plugin for packer 1.5.x

### ISSUE THREAD

**Issue by matayto** [mattiarossi/packer-builder-oracle-ocisurrogate#2]
Great plugin! 

Opening an issue for anyone else that runs across this, but this plugin is currently incompatible with Packer 1.5.x, and it produces the following error:

``` 
packer build -var-file=variables-file.json packer.json

Failed to initialize build 'oracle-ocisurrogate': error initializing builder 'oracle-ocisurrogate': Incompatible API version with plugin. Plugin version: 4, Ours: 5
```

Manually installing packer 1.4.5 fixes.

**Comment by mattiarossi** [comment]
Hi, the current version should already have a mod dependency that requires packer v1.4.5 , I am working on an update to add compatibility with packer 1.5.x

**Comment by mattiarossi** [comment]
And yes, it should be stated as a requirement in the README and in the example usage
